# Build settings
markdown: redcarpet
highlighter: pygments

# Site settings
# title: "A technical notebook"
description: > # this means to ignore newlines until "email:"

email: chloedonegan@gmail.com
#blog logo
logo: "/assets/images/hello-world.png"
# blog cover
cover: "/assets/images/yehaa.jpg"

name: 'Chloë Donegan'
author: 'Chloë Donegan'
author_image: "/assets/images/IMG_2852.jpeg"

paginate:	5

url: "http://csharpd.github.io" # the base hostname & protocol for your site
baseurl: ""

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/thisischloed
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: //www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/csharpd
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
